### ISSUE TITLE
[Bug]: dify-agent在钉钉中无回复

### ISSUE THREAD

**Issue by tianqi888** [RockChinQ/LangBot#1287]
### 消息平台适配器

其他（或暂未使用）

### 运行环境

v3.4.13、win11、docker、Python 3.13.2

### 异常情况

dify-agent在钉钉中无回复或回复不全

![Image](https://github.com/user-attachments/assets/ba8dae4b-2d49-4d3f-80bc-a1140a247ff9)
![Image](https://github.com/user-attachments/assets/39ff98cb-72c0-41d4-ab66-8f8d8a238a3c)
![Image](https://github.com/user-attachments/assets/d72b9041-52f0-4970-ab75-6a500cd2424e)

### 复现步骤

配置好钉钉机器人，以及修改好项目对应的dify-agent参数，向钉钉机器人提问

**Comment by wangcham** [comment]
可以发一下platform.json里的钉钉配置项吗

**Comment by tianqi888** [comment]
@wangcham 这里
```json

{
  "at-sender": false,
  "force-delay": {
    "max": 0,
    "min": 0
  },
  "hide-exception-info": true,
  "long-text-process": {
    "font-path": "",
    "strategy": "forward",
    "threshold": 2560
  },
  "platform-adapters": [
    {
      "adapter": "nakuru",
      "enable": false,
      "host": "127.0.0.1",
      "http_port": 5700,
      "token": "",
      "ws_port": 8080
    },
    {
      "access-token": "",
      "adapter": "aiocqhttp",
      "enable": true,
      "host": "0.0.0.0",
      "port": 2280
    },
    {
      "adapter": "qq-botpy",
      "appid": "",
      "enable": false,
      "intents": [
        "public_guild_messages",
        "direct_message"
      ],
      "secret": ""
    },
    {
      "adapter": "qqofficial",
      "appid": "1234567890",
      "enable": false,
      "port": 2284,
      "secret": "xxxxxxx",
      "token": "abcdefg"
    },
    {
      "EncodingAESKey": "",
      "adapter": "wecom",
      "contacts_secret": "",
      "corpid": "",
      "enable": false,
      "host": "0.0.0.0",
      "port": 2290,
      "secret": "",
      "token": ""
    },
    {
      "adapter": "lark",
      "app_id": "cli_abcdefgh",
      "app_secret": "XXXXXXXXXX",
      "bot_name": "LangBot",
      "enable": false,
      "enable-webhook": false,
      "encrypt-key": "xxxxxxxxx",
      "port": 2285
    },
    {
      "adapter": "discord",
      "client_id": "1234567890",
      "enable": false,
      "token": "XXXXXXXXXX"
    },
    {
      "adapter": "gewechat",
      "app_id": "",
      "callback_url": "http://your-callback-url:2286/gewechat/callback",
      "enable": false,
      "gewechat_file_url": "http://your-gewechat-server:2532",
      "gewechat_url": "http://your-gewechat-server:2531",
      "port": 2286,
      "token": ""
    },
    {
      "AppID": "",
      "AppSecret": "",
      "EncodingAESKey": "",
      "LoadingMessage": "AI正在思考中，请发送任意内容获取回复。",
      "Mode": "drop",
      "adapter": "officialaccount",
      "enable": false,
      "host": "0.0.0.0",
      "port": 2287,
      "token": ""
    },
    {
      "adapter": "dingtalk",
      "client_id": "dingdmepmxxxxx",
      "client_secret": "wuJEC-gTXe32nHOoyRE5yySJI3wnHsf9ByGjxxxxxxxxxxSfe-p5",
      "enable": true,
      "markdown_card": true,
      "robot_code": "dingdmepmxxxxxxxxx",
      "robot_name": "langbot"
    },
    {
      "adapter": "telegram",
      "enable": false,
      "markdown_card": false,
      "token": ""
    },
    {
      "adapter": "slack",
      "bot_token": "",
      "enable": true,
      "port": 2288,
      "signing_secret": ""
    }
  ],
  "quote-origin": false,
  "track-function-calls": true
}

```

**Comment by RockChinQ** [comment]
麻烦粘贴一下你的dify应用的dsl

<img width="316" alt="Image" src="https://github.com/user-attachments/assets/18e675b3-03b8-4b44-a6b8-8e8a8a586a50" />

**Comment by tianqi888** [comment]
@RockChinQ  这里
```yml
app:
  description: ''
  icon: copyright
  icon_background: '#E4FBCC'
  mode: agent-chat
  name: 助手
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/ollama:0.0.3@9ded90ac00e8510119a24be7396ba77191c9610d5e1e29f59d68fa1229822fc7
kind: app
model_config:
  agent_mode:
    enabled: true
    max_iteration: 1
    prompt: null
    strategy: react
    tools:
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 8b7e369a-1b03-48e5-bffd-66e2585f2448
      provider_name: 代码执行查询接口
      provider_type: workflow
      tool_label: 代码执行查询接口
      tool_name: query_sql_fy
      tool_parameters:
        sql: ''
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets:
      - dataset:
          enabled: true
          id: c0276aca-db46-4125-8922-ef6cbec95a40
    reranking_enable: false
    reranking_mode: weighted_score
    reranking_model:
      reranking_model_name: ''
      reranking_provider_name: ''
    retrieval_model: multiple
    top_k: 4
    weights:
      keyword_setting:
        keyword_weight: 0.3
      vector_setting:
        embedding_model_name: bge-m3:latest
        embedding_provider_name: langgenius/ollama/ollama
        vector_weight: 0.7
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    allowed_file_extensions:
    - .JPG
    - .JPEG
    - .PNG
    - .GIF
    - .WEBP
    - .SVG
    - .MP4
    - .MOV
    - .MPEG
    - .MPGA
    allowed_file_types: []
    allowed_file_upload_methods:
    - remote_url
    - local_file
    enabled: false
    image:
      detail: high
      enabled: false
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
    number_limits: 3
  model:
    completion_params:
      stop: []
    mode: chat
    name: qwen2.5-coder
    provider: langgenius/ollama/ollama
  more_like_this:
    enabled: false
  opening_statement: 您可以查询有关库存的相关信息。
  pre_prompt: "提示词"
  prompt_type: simple
  retriever_resource:
    enabled: false
  sensitive_word_avoidance:
    enabled: false
  speech_to_text:
    enabled: false
  suggested_questions:
  - 总数
  suggested_questions_after_answer:
    enabled: true
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form: []
version: 0.1.5

```
