### ISSUE TITLE
[Bug]: 无法调用mcp工具

### ISSUE THREAD

**Issue by lonevle** [RockChinQ/LangBot#1493]
### Runtime environment

v4.0.4, python3.12, docker

### Exception

无法触发调用工具，在Cherry Studio里测试是正常的
### 模型配置， 已启用函数调用
![Image](https://github.com/user-attachments/assets/b0ccd0b8-e727-403b-814f-cae35c4b4ba7)
###  mcp已经配置，并且无法调用
![Image](https://github.com/user-attachments/assets/969e5a23-2a50-4839-b63a-b471724e1a33)
### Cherry Studio正常调用
![Image](https://github.com/user-attachments/assets/2267f894-4237-4244-8b37-d27a9d3de454)

**Comment by RockChinQ** [comment]
<img width="709" alt="Image" src="https://github.com/user-attachments/assets/52a4322a-1ec2-4745-a230-58685842e098" />
我这里看 r1没标tools标签

**Comment by lonevle** [comment]
## 我重新拉取一个模型，qwen3:8b，上面有tools标签，还是无法调用工具
![Image](https://github.com/user-attachments/assets/f6826001-1224-43d8-a0f3-dfba65c789f2)
## 这是修改后的配置
![Image](https://github.com/user-attachments/assets/6c0394bb-99f9-4283-aabd-0b409f063802)
## 现在还是无法调用工具
![Image](https://github.com/user-attachments/assets/94d39d75-d685-4996-bd8b-dd9b9489912f)

**Comment by RockChinQ** [comment]
发一下你的mcp配置我测一下？

**Comment by lonevle** [comment]
### mcp配置
```yaml
mcp:
    servers:
    -   args:
        - --directory
        - /mcp/test
        - run
        - main.py
        command: uv
        enable: true
        env: {}
        mode: stdio
        name: MCP
```

### mcp服务
```python
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("工具")

@mcp.tool()
def del_invoice(invoice_number: str) -> str:
    """
    传入发票号码删除发票, 返回执行结果
    """
    if invoice_number == "123456":
        return f"删除发票{invoice_number}成功"
    else:
        return f"删除发票{invoice_number}失败"


def main():
    mcp.run(transport='stdio')


if __name__ == "__main__":
    main()
```
